name: learn-github-actions
on: push
jobs:
 build:
   runs-on: ubuntu-latest
steps:
- user: actions repo
- uses: actions/checkout@v4
- name: use node.js
- uses: actions/setup-node@v4
   with:
node-version: '20.x'
- run: npm install
- run: npm run build
